name: Daily Keep-Alive Commit

on:
  # ── specific minute & hour (07:15 UTC) once a day ──
  schedule:
    - cron: '15 7 * * *'
  workflow_dispatch:        # let you run it manually for testing

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # allow the job to push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ── required step whose name contains your email ──
      - name: Ping by 22f1000662@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > .daily-ping.txt

      - name: Commit and push update
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .daily-ping.txt
          # --allow-empty ensures a commit even if timestamp unchanged
          git commit --allow-empty -m "Automated daily commit [skip ci]"
          git push
